dist: focal
language: ruby
cache: bundler
rvm:
  - 3.1.2
notifications:
  email: false
before_install:
  - gem update --system --no-document
  - gem install bundler --no-document
script:
  - bundle exec rubocop
  - bundle exec rspec spec
