dist: focal
language: ruby
cache: bundler
rvm:
  - 3.1.1
notifications:
  email: false
before_install:
  - gem update --system --no-document
  - gem install bundler --no-document
script:
  - bundle exec rubocop
  - bundle exec rspec spec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
